### ISSUE TITLE
Validator declines e164 format number

### ISSUE THREAD

**Issue by Spring3** [dial-once/node-phone-utils#28] opened 2017-11-08 19:04 UTC
```
Error: Number: +5548996607945 is not considered a valid e164 formatted phone number.
    at /Users/macbook/Programming/JS/service-phone-number/node_modules/node-phone-utils/lib/providers/hlr-lookups-provider.js:54:21
    at new Promise (<anonymous>)
    at HLRLookupsProvider.hlrLookup (/Users/macbook/Programming/JS/service-phone-number/node_modules/node-phone-utils/lib/providers/hlr-lookups-provider.js:49:10)
```

**Comment by mrister** [comment] 2017-11-08 21:56
@Spring3 On what code and what version of this lib you tested?

I tested  with :
`var provider = new HLRLookupsProvider('hrl', 'username', 'password', console);`
`provider.hlrLookup('+5548996607945').then(console.log).catch(console.error)`

and got a **valid** hlr response.

I think you tested on an outdated version of this library.

**Comment by Spring3** [comment] 2017-11-09 00:43
v2.1.1

**Comment by mrister** [comment] 2017-11-09 13:01
🤔  OK we will investigate, please provide a code sample showing the failure.

**Comment by Spring3** [comment] 2017-11-09 14:03
It works fine for me if there is a small amount of requests to the hlr lookup function. However, when I had 1k of messages in rabbitmq and for each message, I did an hlr lookup, it sometimes ended up with this
![screen shot 2017-11-09 at 03 03 56](https://user-images.githubusercontent.com/4171202/32609147-4d3dd4f8-c567-11e7-8518-b66b06542658.png)

**Comment by ykhatal** [comment] 2017-11-09 14:13
I did some tests on my side too, and i get `true` each time. So not sure about what the issue is

**Comment by mrister** [comment] 2017-11-09 14:55
This may be due to throttling on the provider side ...for the larger amount of numbers, I think the bulk call should be used.

**Comment by ykhatal** [comment] 2017-11-30 11:54
here is my analysis:

The Error thrown is `Number XX is not is not considered a valid e164 formatted phone number.`
it's thrown at this [line](https://github.com/dial-once/node-phone-utils/blob/develop/lib/providers/hlr-lookups-provider.js#L51)
which mean that the phont number isn't valid, so there's nothing to do with the hlrLookup.

@mrister updated the googlelibphonenumber to the latest, and the issue seems to be resolved.

On my side and after doing some tests on the `internal-service` with 2000 message (Don't worry i mocked the call to the hrl to avoid paying for that)
i got all my request successful.

When i tested with the phone number mentioned by @Spring3 which is `+336208761914` i got the same error.
That's ok since the phone number has 1 digit more, when I removed the last one i got a successful response.

So for me there is no issue there, but to confirm that, I captured the production logs of the `internal-service` and i see no error of that kind.

So i guess that we can close it for now, and reopen if the issue occur again and the phone number is valid.

**Closed as completed by ykhatal** 2017-11-30 11:54 UTC
Labels: bug
